const PROPERTY_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  AVAILABLE: 'AVAILABLE',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
  SOLD: 'SOLD',
  RENTED: 'RENTED',
  UNAVAILABLE: 'UNAVAILABLE',
  ARCHIVED: 'ARCHIVED'
};

const INQUIRY_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  CLOSED: 'CLOSED'
};

const APPOINTMENT_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

module.exports = {
  PROPERTY_STATUSES,
  INQUIRY_STATUSES,
  APPOINTMENT_STATUSES
};
